apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name  }}
  labels:
    run: {{ .Release.Name }}
spec:
  containers:
  - image: {{ .Values.image }}:{{ .Values.tag }}
    name: {{ .Values.image }}
    ports:
    - containerPort: {{ .Values.port }}